### ISSUE TITLE
typo in repository name?

### ISSUE THREAD

**Issue by joewiz** [cmarchand/highlightJS-saxon-extension#1]
A very cool project!

The repository name, highligtJS-saxon-extension, appears to contain a typo: it's `ligt` instead of `light` (missing 2nd `h`).

**Comment by cmarchand** [comment]
Thanks a lot !

You are correct, that's a typo ! But as this project has been referenced in various ML and on Twitter, I won't change it's name, and its URL.

**Comment by joewiz** [comment]
As you wish, but GitHub institutes redirects when repositories are renamed: https://github.blog/2013-05-16-repository-redirects-are-here/ and https://docs.github.com/en/github/administering-a-repository/renaming-a-repository.

**Comment by cmarchand** [comment]
Oh oh !

**Comment by cmarchand** [comment]
Done. Thanks a lot !

**Comment by joewiz** [comment]
@cmarchand Excellent! Sure, and thank you!
